services:
  postgres:
    image: postgres:15-alpine
    container_name: manager_db
    environment:
      POSTGRES_DB: manager
      POSTGRES_USER: luis.gf
      POSTGRES_PASSWORD: provisional
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - manager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luis.gf -d manager"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8085:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/manager
      SPRING_DATASOURCE_USERNAME: luis.gf
      SPRING_DATASOURCE_PASSWORD: provisional
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      #SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #SPRING_JPA_SHOW_SQL: false
      #SPRING_PROFILES_ACTIVE: docker
      #LOGGING_LEVEL_COM_PROJECTMANAGER: INFO
      #LOGGING_LEVEL_ROOT: WARN
      #SERVER_PORT: 8080
    networks:
      - manager_network


volumes:
  pgdata:
    driver: local

networks:
  manager_network:
    driver: bridge